# This workflow is triggered when a new version is published to npm. It checks out the code, sets up Node.js, 
# and publishes the package to npm using the provided authentication token.
name: Publish to npm

on:
  push:
    branches: [main]
    paths:
      - "package.json" # only run when version actually changes

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
